import type { Metadata } from 'next';

import './globals.css';

import React from 'react';
import { ReactQueryProvider } from 'src/shared/providers/ReactQueryProvider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ReactQueryProvider>{children}</ReactQueryProvider>;
}
